language: php
sudo: false

php:
  - 5.5

mysql:
  database: dkan_travis
  username: root
  encoding: utf8

install:
  - cd test
  - composer install
  - mysql -e 'create database dkan_travis;'

  # Install latest Drush 7.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction drush/drush:dev-master
  - composer global require --no-interaction youngj/httpserver:*

before_script:
  # Install DKAN
  - cd ~
  - git clone https://github.com/NuCivic/dkan-drops-7.git
  - cd dkan-drops-7
  - git clone https://github.com/NuCivic/open_data_schema_map.git
  - mv open_data_schema_map sites/all/modules/.

  - drush si dkan --sites-subdir=default --db-url=mysql://root:@127.0.0.1:3306/dkan_travis --account-name=admin --account-pass=admin  --site-name="DKAN" install_configure_form.update_status_module='array(FALSE,FALSE)' --yes
  - drush --quiet --yes --root=$PWD runserver :8888 > /dev/null 2>&1 &

  - cp -r /home/travis/build/NuCivic/open_data_federal_extras sites/all/modules/.
  - drush en -y open_data_federal_extras
  - drush cc all --yes
  - drush vset 'dkan_dataset_form_additional_info' 0
  - cd sites/all/modules/open_data_federal_extras/test

script:
  - bin/behat
